# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'plapla' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  
  pod 'RealmSwift'
  pod 'SwiftGen'
  pod 'SwiftFormat/CLI', :configurations => ['Debug']
  pod 'SwiftLint'

  # Pods for plapla

end